version: "3.7"

volumes:
  data:
    external: true
    name: "rinnegan-database-volume"

networks:
  database:
    external: true
    name: "rinnegan-database-network"
  backend:
    external: true
    name: "rinnegan-backend-network"
  frontend:
    external: true
    name: "rinnegan-frontend-network"

secrets:
  database-password:
    external: true
  database-user:
    external: true

services:
  postgres-master:
    image: onlinejudge95/rinnegan-postgres
    networks:
      - database
    secrets:
      - database-password
      - database-user
    volumes:
      - data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.labels.type == master
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/database-password
      POSTGRES_USER_FILE: /run/secrets/database-user

  postgres-slave:
    image: onlinejudge95/rinnegan-postgres
    networks:
      - database
    secrets:
      - database-password
      - database-user
    volumes:
      - data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.labels.type == slave
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/database-password
      POSTGRES_USER_FILE: /run/secrets/database-user

  visualizer:
    image: dockersamples/visualizer
    stop_grace_period: 20s
    networks:
      - backend
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
