version: "3.8"

volumes:
  data:
    external: true
    name: "rinnegan-database-volume"

networks:
  database:
    external: true
    name: "rinnegan-database-network"

secrets:
  database-password:
    external: true
  database-user:
    external: true

services:
  postgres:
    image: bitnami/postgresql-repmgr:11-debian-10
    networks:
      - database
    ports:
      - 5432
    secrets:
      - database-password
      - database-user
    volumes:
      - data:/var/lib/postgresql/data
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == worker
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/database-password
      POSTGRES_USER_FILE: /run/secrets/database-user

  visualizer:
    image: dockersamples/visualizer
    stop_grace_period: 20s
    networks:
      - backend
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
